# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: e8ce68a55a9953a6bc696c6215934b0916af9c9c96ab4bde10cc3621bcc7925ef07e2424e41609314f52c9bf3dc4e04deb6626d6f3002223004cd1087d0e2087

test:
  domain_name: example.com 
  secret_key_base: d051d215ec400c0ef9c99482088420caa3a1b81241524c85866b0fe906a41683047a182ef9fc3123e0f64d54cd90f871fc3a9fbea0d7f5454bc8e1429aebc5a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
